# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'radio' do
  pod 'StreamingKit', :git => 'https://github.com/tlenclos/StreamingKit.git', :branch => 'icecast'

end

